development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: QuizWar_development
  pool:     5
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: QuizWar_test
  pool:     5
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: QuizWar_production
  pool:     5
  template: template0
